# Make a request to “theyfightcrime.org”
# Extract the two characters generated by the website from the HTML
# Import the packages
import requests
import lxml
from lxml import etree

# Save the male characters in one text ﬁle 
# Save the female characters in another text ﬁle 
# Repeat 50 times
with open("male.txt","w") as m:
    with open("female.txt","w") as f:
        for i in range(0,50):
            r = requests.get("https://theyfightcrime.org/") 
            root = etree.HTML(r.content)
            words = root.xpath("//p//text()")
            characters = words[1]
            male = characters.split('She')[0]
            m.writelines(male+'\n')
            female = characters.split('She')[1]
            female = female.split('They')[0]
            female = 'She' + female
            f.writelines(female+'\n')


